# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Zhanwei Gao
description: >- # this means to ignore newlines until "baseurl:"
  Zhanwei Gao's website
baseurl: "" # the subpath of the site
url: "https://zhanweigao.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Projects
    - name: Blog
    - name: Pursuits

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: chaitanyasuma@gmail.com
      link: mailto:chaitanyasuma@gmail.com
  follow:
    - name: Twitter
      link: http://twitter.com/chaitanyasumaa
      username: "@chaitanyasumaa"
    - name: LinkedIn
      link: http://linkedin.com/in/Chaitanyasuma
    - name: GitHub
      link: http://github.com/Chaitanyasuma
    - name: Medium
      link: https://chaitanyasuma.medium.com/

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
